linux_test_task:
  container:
    image: ghcr.io/flipstone/haskell-tools:debian-ghc-9.10.3-1e1d10c
    cpu: 6
    memory: 6G
  env:
    matrix:
      - GHC_VERSIONS: 9.4.8
        STACK_YAMLS:
      - GHC_VERSIONS: 9.6.7
        STACK_YAMLS:
      - GHC_VERSIONS: 9.8.4
        STACK_YAMLS:
      - GHC_VERSIONS: 9.10.3
        STACK_YAMLS:
      - GHC_VERSIONS: 9.12.2
        STACK_YAMLS:
      - GHC_VERSIONS:
        STACK_YAMLS: stack.yaml
  linux_stack_cache:
    folder: ~/.stack
    fingerprint_script:
      - cat stack.yaml stack.yaml.lock henforcer.cabal
    populate_script:
      - apt update
      - apt install bmake
      - export PATH=$PATH:/root/.local/bin:/root/.ghcup/bin
      - bmake setup-stack
  linux_ghcup_cache:
    folder: /usr/local/.ghcup
    fingerprint_script:
      - cat Makefile
    populate_script:
      - apt update
      - apt install bmake
      - export PATH=$PATH:/root/.local/bin:/root/.ghcup/bin
      - bmake setup-ghc
  linux_cabal_cache:
    folder: ~/.local/state/cabal
    fingerprint_script:
      - cat Makefile henforcer.cabal
    populate_script:
      - apt update
      - apt install bmake
      - export PATH=$PATH:/root/.local/bin:/root/.ghcup/bin
      - bmake setup-cabal
  install_script:
    - apt update
    - apt install bmake
    - export PATH=$PATH:/root/.local/bin:/root/.ghcup/bin
    - bmake setup
  test_script:
    - export PATH=$PATH:/root/.local/bin:/root/.ghcup/bin
    - bmake ci
  upload_caches:
    - linux_stack
    - linux_ghcup
    - linux_cabal

freebsd_test_task:
  freebsd_instance:
    image_family: freebsd-15-0
    cpu: 6
    memory: 6G
  freebsd_stack_cache:
    folder: ~/.stack
    fingerprint_script:
      - cat stack.yaml.lock henforcer.cabal
  freebsd_cabal_cache:
    folder: ~/.local/state/cabal
    fingerprint_script:
      - cat Makefile henforcer.cabal
  freebsd_ghcup_cache:
    folder: /usr/local//.ghcup
    fingerprint_script:
      - cat Makefile
    populate_script:
      - pkg install -y hs-stack hs-cabal-install curl
      - curl -o /usr/local/bin/ghcup https://downloads.haskell.org/\~ghcup/0.1.50.2/x86_64-portbld-freebsd-ghcup-0.1.50.2
      - chmod +x /usr/local/bin/ghcup
      - export PATH=$PATH:/.local/bin:/.ghcup/bin
      - export GHC_VERSIONS=9.12.2
      - export STACK_YAMLS=
      - make setup-cabal
  upload_caches:
    - freebsd_ghcup
  install_script:
    - pkg install -y hs-stack hs-cabal-install curl
    - curl -o /usr/local/bin/ghcup https://downloads.haskell.org/\~ghcup/0.1.50.2/x86_64-portbld-freebsd-ghcup-0.1.50.2
    - chmod +x /usr/local/bin/ghcup
    - export PATH=$PATH:/.local/bin:/.ghcup/bin
    - export GHC_VERSIONS=9.12.2
    - export STACK_YAMLS=
    - make setup-cabal
  test_script:
    - export PATH=$PATH:/.local/bin:/.ghcup/bin
    - export GHC_VERSIONS=9.12.2
    - export STACK_YAMLS=
    # no reason to test everything, like formatting, on every platform
    - make test-cabal
  upload_caches:
    - freebsd_cabal
