name:                modulint
version:             0.1.0.0
github:              "flipstone/modulint"
license:             BSD3
author:              "Flipstone Technology Partners"
maintainer:          "development@flipstone.com"
copyright:           "2020 Flipstone Technology Partners"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flipstone/modulint#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers >= 0.6 && < 0.7
- dhall >= 1.28 && < 1.38
- directory >= 1.3 && < 1.4
- file-embed >= 0.0 && < 0.1
- filepath >= 1.4 && < 1.5
- haskell-src-exts >= 1.20 && < 1.24
- optparse-applicative >= 0.14 && < 0.17
- unix >= 2.7 && < 2.8
- text

library:
  source-dirs: src

ghc-options: -Wall -Werror

executables:
  modulint:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modulint
tests:
  modulint-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modulint
    - HUnit

