name:                modulo
version:             0.1.0.0
github:              "flipstone/modulo"
license:             BSD3
author:              "Flipstone Technology Partners"
maintainer:          "development@flipstone.com"
copyright:           "2020 Flipstone Technology Partners"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flipstone/modulo#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- haskell-src-exts
- unix

library:
  source-dirs: src

ghc-options: -Wall -Werror

executables:
  modulo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modulo

tests:
  modulo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modulo

