[forAnyModule]
allowedOpenUnaliasedImports = 1
maximumExportsPlusHeaderUndocumented = 1
minimumExportsPlusHeaderDocumented = 0
maximumExportsWithoutSince = 0
minimumExportsWithSince = 1
moduleHeaderCopyrightMustExistNonEmpty = true
moduleHeaderDescriptionMustExistNonEmpty = true
moduleHeaderLicenseMustExistNonEmpty = true
moduleHeaderMaintainerMustExistNonEmpty = false
encapsulatedTrees = [ "Service.ThirdPartyPetsSite"]
treeDependencies = [ {moduleTree = "Control.Monad", dependencies = ["PetStore"], note= "This is nonsensical but shows the kind of things we can here."} ]
allowedAliasUniqueness = { allAliasesUniqueExcept = [ "Export" ], note = "Only 'Export' is allowed to be repeated so that we can create re-export modules with a single export of the form 'module Export'." } # The 'note' here is arbitrary but shows a real world use case

[[forAnyModule.allowedQualifications]]
module = "UnliftIO"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = { qualifiedPre = true, qualifiedPost = true }
alias = "Foo"
packageQualified = "unliftio"

[[forAnyModule.allowedQualifications]]
module = "Prelude"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = { qualifiedPre = true, qualifiedPost = true, unqualified = true}

[[forAnyModule.allowedQualifications]]
module = "Data.List"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = { qualifiedPre = true}
alias = "L"
note = "List must always be imported as L when prepositive for reasons"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = { qualifiedPre = true}
alias = "LPost"
note = "List must always be imported as LPost when postpositive for reasons"

[[forAnyModule.allowedQualifications]]
module = "Data.Bool"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = {unqualified = true}
safe=true

[[forAnyModule.allowedQualifications]]
module = "Control.Arrow"
[[forAnyModule.allowedQualifications.importScheme]]
# this prevents import of Control.Arrow as no schemes will be allowed.
qualified = { }

[[forAnyModule.allowedQualifications]]
module = "Data.Text"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = {qualifiedPre = true}
alias = "T"
packageQualified = "text"

[[forAnyModule.allowedQualifications]]
module = "PetStore.Pet.Model"
[[forAnyModule.allowedQualifications.importScheme]]
qualified =  {qualifiedPost = true}
alias="PetModel"
[[forAnyModule.allowedQualifications.importScheme]]
qualified = {unqualified = true}
# safe = false

[[forPatternModules]]
pattern = "Pet*.Store.**"
allowedOpenUnaliasedImports = 5000
maximumExportsPlusHeaderUndocumented = 5000

[[forPatternModules]]
pattern = "Pet*.Food.**"
[forPatternModules.rulesToIgnore]
allowedOpenUnaliasedImports = true

[[forPatternModules]]
pattern = "Pet*.**.Model"
allowedOpenUnaliasedImports = 0

[[forPatternModules]]
# Note this will not be applied to PetStore.Pet.Model! The following pattern overlaps with the above
# and the first matching pattern rule is the one that will win.
pattern = "**.Model"
allowedOpenUnaliasedImports = 1

[[forSpecifiedModules]]
module ="PetStore.Store.Account"
allowedOpenUnaliasedImports = 3

[[forSpecifiedModules]]
module ="PetStore.Store"
allowedOpenUnaliasedImports = 2
moduleHeaderCopyrightMustExistNonEmpty = true
[forSpecifiedModules.rulesToIgnore]
